# Generated by Django 4.1.4 on 2022-12-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChildrentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeddyBear.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=500, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('material', models.CharField(max_length=255, null=True)),
                ('initial_price', models.FloatField(default=0)),
                ('curent_price', models.FloatField(null=True)),
                ('like', models.IntegerField(blank=True, null=True)),
                ('amount_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_product', models.BooleanField(default=False)),
                ('hot_product', models.BooleanField(default=False)),
                ('childrent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeddyBear.childrentcategory')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('name', 'childrent_category')},
            },
        ),
    ]
